# mandatory parameters
[path]
source = "/media/DataQubic/**/*(MoonScan)*"

[optional]
destination = "cr_results"
remove_drift = false
mask = "../masks"
vertical_points = 3
exponential_points = 6
analysis_type = "range"
tes = [10, 100]
remove_files = true
deconvolution = false
dpi = 300