# mandatory parameters
[path]
source = "/media/DataQubic/**/*(MoonScan)*"

[optional]
destination = "cr_results"
remove_drift = false
mask = "../masks"
vertical_points = 3
exponential_points = 6
analysis_type = "sequence"
tes = [1, 3, 5, 6, 7, 10]
remove_files = true
save_results = false
dpi = 300