# mandatory parameters
[path]
source = "/media/DataQubic/**/*(ScanFast)*"

[optional]
destination = "cr_results"
remove_drift = false
mask = "../masks"
vertical_points = 3
exponential_points = 6
analysis_type = "all"
tes = [-1]
remove_files = true
deconvolution = true
dpi = 300